### ISSUE TITLE
Ability to add custom locations on the map

### ISSUE THREAD

**Issue by kirananto** [kirananto/SupplyInfo#2]
Right now we only have ability to tag his/her current location for two scenarios
1. Posting a location
2. Viewing the listing page

We need to bring in the ability for the user to change location in both places.

**Comment by favazkandath** [comment]
@kirananto I'll be taking this issue

**Comment by kirananto** [comment]
Awesome..  :tada:

**Comment by kirananto** [comment]
Since it's done.. marking as closed
